### ISSUE TITLE
Lots of 404s

### ISSUE THREAD

**Issue by zeke** [joshuapinter/cntral_desktop_releases#1]
Hi @joshuapinter 👋 

I'm noticing a lot of 404s coming from the update.electronjs.org service.

https://update.electronjs.org/joshuapinter/cntral_desktop_releases/darwin/0.0.1

It's failing because:

> No updates found (needs asset matching *{mac,darwin,osx}*.zip in public repository)

Please let me know if you need some help getting this set up correctly.

**Comment by joshuapinter** [comment]
Hi Zeke,

Sorry about that. We were testing in development and then removed the
releases after the tests were successful. We’re all good and that should
get cleared up right away here.

Thanks for checking in!

Joshua

-- 
*Joshua Pinter*
<http://cntr.al/?ref=emailSignature>
Centralize Your Regulatory Inspections.
[image: NTWRK] <http://ntwrkapp.com/?ref=emailSignature>
Have Better Relationships.
______________________________________________

On May 25, 2018 at 4:32:01 PM, Zeke Sikelianos (notifications@github.com)
wrote:

Hi @joshuapinter <https://github.com/joshuapinter> 👋

I'm noticing a lot of 404s coming from the update.electronjs.org service.

https://update.electronjs.org/joshuapinter/cntral_desktop_releases/darwin/0.0.1

It's failing because:

No updates found (needs asset matching *{mac,darwin,osx}*.zip in public
repository)

Please let me know if you need some help getting this set up correctly.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/joshuapinter/cntral_desktop_releases/issues/1>, or mute
the thread

**Comment by zeke** [comment]
👍
